# Generated by Django 5.0.3 on 2024-04-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_field',
            new_name='posted_date',
        ),
    ]
